/* ========================================
   TrainLytics — Internationalization (i18n)
   ======================================== */

let _lang = localStorage.getItem('trainlytics_lang') || 'de';

const TRANSLATIONS = {
de: {
    // Month names
    months: ['Jan','Feb','Mär','Apr','Mai','Jun','Jul','Aug','Sep','Okt','Nov','Dez'],
    locale: 'de-DE',

    // Splash
    splash_welcome: 'Du trainierst bei <strong>Micky</strong> und möchtest deine Daten tracken?',
    splash_sub: 'Hier bist du richtig.',

    // Login
    login_tagline: 'Deine App, um Training und Analytics zu vereinen',
    login_sub: 'Melde dich an, um loszulegen',
    login_name_label: 'Dein Name',
    login_name_ph: 'z.B. Usain',
    login_pw_label: 'Passwort',
    login_pw_ph: 'Passwort eingeben',
    login_btn: 'Einloggen',
    lang_label: 'Sprache',

    // Coach
    coach_dashboard: 'Coach Dashboard',
    coach_logout: 'Abmelden',
    tab_overview: 'Übersicht',
    tab_plan: 'Plan',
    tab_pain: 'Schmerz',
    ranking: '🏆 Ranking',
    coach_badge: 'COACH',
    single_view: '📊 Einzelübersicht',
    select_athlete: 'Athlet auswählen',
    please_select: '-- Bitte wählen --',
    assign_plan: '📋 Trainingsplan zuweisen',
    athlete: 'Athlet',
    week_from: 'Woche ab',
    plan_notes_label: 'Hinweise',
    plan_notes_label_hint: '(optional)',
    plan_notes_ph: 'Allgemeine Hinweise für die Woche…',
    plan_notes_full: 'Hinweise <span class="label-hint">(optional)</span>',
    assign_plan_btn: 'Plan zuweisen',
    day_mon: 'Montag', day_tue: 'Dienstag', day_wed: 'Mittwoch', day_thu: 'Donnerstag',
    day_fri: 'Freitag', day_sat: 'Samstag', day_sun: 'Sonntag',
    day_mon_s: 'Mo', day_tue_s: 'Di', day_wed_s: 'Mi', day_thu_s: 'Do',
    day_fri_s: 'Fr', day_sat_s: 'Sa', day_sun_s: 'So',
    plan_ph_mon: 'z.B. Sprint 6×50m I2', plan_ph_tue: 'z.B. Kraft', plan_ph_wed: 'z.B. Regeneration',
    plan_ph_thu: 'z.B. Tempolauf 120m NI', plan_ph_fri: 'z.B. Ruhetag', plan_ph_sat: 'z.B. Wettkampf', plan_ph_sun: 'z.B. Frei',
    coach_diary_title: '🩹 Schmerztagebuch',

    // App header
    greeting: 'Hallo',
    settings_title: 'Eigene Trainingsarten',
    logout: 'Abmelden',

    // Main tabs
    tab_training: 'Training',
    tab_calendar: 'Kalender',
    tab_analytics: 'Analytics',
    tab_diary: 'Tagebuch',

    // Training form
    new_session: 'Neue Einheit',
    new_badge: 'NEU',
    date_label: 'Datum',
    time_label: 'Uhrzeit',
    type_label: 'Trainingsart',
    category_label: 'Kategorie',
    description_label: 'Beschreibung',
    description_ph: 'z.B. Koordination, Hürden...',
    intensity_label: 'Intensität',
    times_label: 'Zeiten',
    times_hint: '(in Sekunden)',
    time_ph: 'z.B. 6.85',
    remove_label: 'Entfernen',
    add_time: 'Weitere Zeit',
    run_time: 'Laufzeit',
    minutes_label: 'Minuten',
    minutes_ph: 'z.B. 28',
    seconds_label: 'Sekunden',
    seconds_ph: 'z.B. 45',
    count_label: 'Anzahl Läufe',
    count_ph: 'z.B. 6',
    weight_label: 'Gewicht',
    kg_label: 'Kilogramm',
    reps_label: 'Wiederholungen',
    reps_short: 'Wdh',
    telemark_question: 'Telemarks gemacht?',
    no: 'Nein',
    yes: 'Ja',
    telemark_count: 'Anzahl Telemarks',
    telemark_count_ph: 'z.B. 4',
    exercises_label: 'Übungen',
    exercises_hint: '(abhaken was gemacht wurde)',
    normal: 'Normal',
    pyramid: 'Pyramide',
    kilo: 'Kilo',
    reps_dot: 'Wdh.',
    set_label: 'Satz',
    add_set: 'Satz hinzufügen',
    kniebeugen: 'Kniebeugen',
    waden: 'Waden',
    beuger: 'Beuger',
    bauch: 'Bauch',
    ruecken: 'Rücken',
    exzentrisch: 'Exzentrisch',
    hipthrust: 'Hip Thrust',
    add_type_btn: 'Weitere Trainingsart hinzufügen',
    notes_label: 'Notizen',
    optional_hint: '(optional)',
    notes_ph: 'Wetter, Gefühl, Untergrund …',
    save_btn: 'Speichern',

    // Training types (display names stay same in both languages as they're domain terms)
    type_sprint: 'Sprint (50m)',
    type_tempo120: 'Tempolauf (120m)',
    type_tempo150: 'Tempolauf (150m)',
    type_kraft: 'Kraft',
    type_technik: 'Technik',
    type_joggen: 'Joggen (5km)',
    type_pause: '💤 Pausetag',

    // Sprint categories
    cat_locker: 'Locker',
    cat_submax: 'Sub-Max',
    cat_max: 'Max',
    cat_seil: 'Seil',

    // Technik categories
    cat_huetchen: 'Hütchen',
    cat_schirm: 'Schirm',
    cat_sonstiges: 'Sonstiges',

    // History
    history_title: 'Übersicht',
    filter_all: 'Alle',
    empty_sessions: 'Noch keine Einheiten vorhanden.',
    clock_suffix: 'Uhr',
    pausetag_text: 'Pausetag 💤',
    runs_count: 'Anzahl Läufe',
    telemarks_label: 'Telemarks',
    count_prefix: 'Anzahl',
    delete_title: 'Löschen',

    // Analytics
    dashboard: 'Dashboard',
    analytics_type_label: 'Trainingsart',
    general: 'Allgemein',
    all_categories: 'Alle Kategorien',
    all_intensities: 'Alle Intensitäten',

    // General stats
    stat_season: 'Saison',
    stat_sessions_season: 'Einheiten (Saison)',
    stat_avg_week: 'Ø pro Woche',
    stat_streak: 'Aktuelle Serie (Wo.)',
    stat_total_all: 'Einheiten Gesamt',
    stat_pause_season: 'Pausetage (Saison)',
    stat_last_session: 'Letzte Einheit',

    // Kraft stats
    stat_sessions: 'Einheiten',
    stat_avg_exercises: 'Ø Übungen/Einheit',
    stat_max_kb: 'Max Kniebeugen (kg)',
    stat_max_waden: 'Max Waden (kg)',
    stat_most_exercise: 'Häufigste Übung',

    // Technik stats
    stat_most_category: 'Häufigste Kategorie',

    // Joggen stats
    stat_best_time: 'Bestzeit',
    stat_avg_time: 'Ø Zeit',
    stat_total_km: 'Gesamt km',
    stat_trend: 'Trend',

    // Custom type stats
    stat_custom_most_cat: 'Häufigste Kategorie',
    stat_custom_last: 'Letzte Einheit',

    // Sprint/Tempo stats
    stat_pb: 'Beste Zeit',
    stat_average: 'Durchschnitt',
    stat_last5: 'Letzte 5 ⌀',
    stat_worst: 'Schlechteste',

    // NI stats
    stat_avg_runs: 'Ø Läufe',
    stat_total_runs: 'Gesamt Läufe',
    stat_total_meters: 'Gesamt Meter',
    stat_total_telemarks: 'Gesamt Telemarks',
    stat_avg_telemarks: 'Ø Telemarks',

    // PB
    pb_title: 'Persönliche Bestzeiten – Top 10',

    // Calendar
    next_comp: 'Nächster Wettkampf',
    no_comp_planned: 'Kein Wettkampf geplant',
    add_comp_btn: 'Wettkampf eintragen',
    season_label: 'Saison',
    legend_training: 'Training',
    legend_comp: 'Wettkampf',
    legend_today: 'Heute',
    competitions_title: 'Wettkämpfe',
    no_competitions: 'Noch keine Wettkämpfe eingetragen.',
    today_text: 'Heute!',
    tomorrow_text: 'Morgen!',
    days_left: 'Noch {n} Tage',

    // Diary
    plan_title: '📋 Trainingsplan',
    prev_week: 'Vorherige Woche',
    next_week: 'Nächste Woche',
    add_injury_btn: 'Schmerz / Verletzung eintragen',
    diary_title: '🩺 Schmerztagebuch',
    no_diary_entries: 'Noch keine Einträge vorhanden.',
    pain_overview: '📈 Schmerzübersicht',

    // Delete modal
    delete_modal_title: 'Einheit löschen?',
    delete_modal_text: 'Diese Aktion kann nicht rückgängig gemacht werden.',
    cancel_btn: 'Abbrechen',
    delete_btn: 'Löschen',

    // Competition modal
    comp_modal_title: 'Wettkampf eintragen',
    comp_name_label: 'Name des Wettkampfes',
    comp_name_ph: 'z.B. Hallenstadtmeisterschaft',
    comp_disciplines: 'Disziplinen',
    comp_weitsprung: 'Weitsprung',
    comp_dreisprung: 'Dreisprung',

    // Injury modal
    injury_modal_title: '🩺 Schmerz / Verletzung',
    body_part_label: 'Körperteil',
    body_select: '-- Wählen --',
    body_knee: 'Knie',
    body_thigh: 'Oberschenkel',
    body_calf: 'Wade',
    body_ankle: 'Sprunggelenk',
    body_foot: 'Fuß',
    body_hip: 'Hüfte',
    body_back: 'Rücken',
    body_shoulder: 'Schulter',
    body_achilles: 'Achillessehne',
    body_shin: 'Schienbein',
    pain_level: 'Schmerzlevel (1–10)',
    side_label: 'Seite',
    side_left: 'Links',
    side_right: 'Rechts',
    side_both: 'Beide',

    // Settings
    settings_title_modal: '⚙️ Einstellungen',
    tab_report: '📄 Bericht',
    tab_types: '🏷️ Trainingsarten',
    report_hint: 'Lade eine Zusammenfassung deiner Trainingswoche als PDF-Dashboard herunter.',
    week_label: 'Woche',
    download_pdf: '📥 PDF herunterladen',
    new_type: 'Neue Trainingsart',
    based_on: 'Basiert auf',
    new_category: 'Neue Kategorie',
    name_label: 'Name',
    name_ph: 'z.B. Ausdauer, Dehnen, Hürden',
    emoji_label: 'Emoji',
    emoji_ph: 'z.B. 🏋️ 🧘 🔥',
    color_label: 'Farbe',
    subcategories_label: 'Unterkategorien',
    subcategories_hint: '(kommagetrennt, optional)',
    subcategories_ph: 'z.B. Hürden, Koordination, Sprint',
    track_times: 'Zeiten erfassen?',
    track_reps: 'Wiederholungen erfassen?',
    track_kg: 'Kilogramm erfassen?',
    add_btn: 'Hinzufügen',
    extend_subcats: 'Unterkategorien erweitern',
    new_subcat_label: 'Neue Unterkategorie',
    new_subcat_ph: 'z.B. Hürden, Staffel',
    hide_types_title: 'Trainingsarten ausblenden',
    hide_types_hint: 'Deaktivierte Typen erscheinen nicht im Trainingsformular.',

    // Toast messages
    toast_pw_required: 'Bitte Passwort eingeben',
    toast_pw_wrong: 'Falsches Passwort',
    toast_pw_set: 'Passwort gesetzt ✓',
    toast_login_error_coach: 'Fehler bei Coach-Login',
    toast_login_error: 'Fehler beim Login',
    toast_fill_all: 'Bitte alle Felder ausfüllen',
    toast_select_intensity: 'Bitte Intensität wählen',
    toast_select_sprint_cat: 'Bitte Sprint-Kategorie wählen',
    toast_select_technik_cat: 'Bitte Technik-Kategorie wählen',
    toast_enter_description: 'Bitte Beschreibung eingeben',
    toast_select_category: 'Bitte Kategorie wählen',
    toast_pause_saved: 'Pausetag eingetragen 💤',
    toast_check_exercise: 'Bitte mindestens eine Übung abhaken',
    toast_valid_runtime: 'Bitte gültige Laufzeit eingeben',
    toast_valid_times: 'Bitte gültige Zeiten eingeben',
    toast_enter_count: 'Bitte Anzahl eingeben',
    toast_enter_telemark: 'Bitte Telemark-Anzahl eingeben',
    toast_enter_kg: 'Bitte Kilogramm eingeben',
    toast_saved: 'Gespeichert ✓',
    toast_deleted: 'Gelöscht',
    toast_select_week: 'Bitte Woche auswählen',
    toast_enter_name: 'Bitte Name eingeben',
    toast_name_long: 'Name zu lang (max 30 Zeichen)',
    toast_name_reserved: 'Dieser Name ist reserviert',
    toast_name_taken: 'Name bereits vergeben',
    toast_updated: 'Aktualisiert ✓',
    toast_added: 'Hinzugefügt ✓',
    toast_removed: 'Entfernt',
    toast_exists: 'Existiert bereits',
    toast_name_too_long: 'Name zu lang',
    toast_comp_fill: 'Bitte alle Felder ausfüllen',
    toast_comp_discipline: 'Bitte mindestens eine Disziplin wählen',
    toast_comp_saved: 'Wettkampf gespeichert ✓',
    toast_comp_deleted: 'Wettkampf gelöscht',
    toast_injury_fill: 'Bitte Datum und Körperteil angeben',
    toast_injury_saved: 'Eintrag gespeichert ✓',
    toast_injury_deleted: 'Eintrag gelöscht',
    toast_plan_select: 'Bitte Athlet und Woche wählen',
    toast_plan_fill: 'Bitte mindestens einen Tag ausfüllen',
    toast_plan_assigned_multi: 'Plan an {n} Athleten zugewiesen ✓',
    toast_plan_assigned: 'Plan zugewiesen ✓',
    toast_plan_error: 'Fehler beim Speichern',
    toast_plan_deleted: 'Plan gelöscht',
    toast_plan_delete_error: 'Fehler beim Löschen',
    toast_pdf_done: 'PDF heruntergeladen',

    // Confirm messages
    confirm_delete_type: 'Trainingsart "{name}" wirklich löschen?',
    confirm_delete_plan_all: 'Plan ({date}) für ALLE {n} Athleten wirklich löschen?',
    confirm_delete_plan: 'Plan ({date}) für {name} wirklich löschen?',
    confirm_delete_plan_athlete: 'Plan für Woche ab {date} wirklich löschen?',

    // Dynamic text
    no_data: 'Keine Daten',
    no_data_available: 'Keine Daten vorhanden.',
    time_header: 'Zeit',
    date_header: 'Datum',
    note_header: 'Notiz',
    no_athletes: 'Keine Athleten vorhanden.',
    total_sessions: 'Einheiten Gesamt',
    avg_per_week_season: 'Ø Einheiten pro Woche (Saison {label})',
    sessions_season: 'Einheiten Saison ({label})',
    no_entries_athlete: 'Keine Einträge vorhanden.',
    stat_total: 'Gesamt',
    sprint_pb: 'Sprint PB',
    max_kb_kg: 'Max KB (kg)',
    additional_type: 'Weitere Trainingsart',

    // Chart titles
    chart_monthly_season: 'Einheiten pro Monat (Saison {label})',
    chart_type_dist: 'Verteilung nach Trainingsart',
    chart_weekly_season: 'Einheiten pro Woche (Saison)',
    chart_weekday: 'Trainingstage (Wochentag)',
    chart_monthly_all: 'Einheiten pro Monat (Gesamtverlauf)',
    chart_intensity_dist: 'Intensitätsverteilung (Tempolauf, Saison)',
    chart_kraft_monthly: 'Krafteinheiten pro Monat',
    chart_exercise_freq: 'Übungshäufigkeit (Gesamt)',
    chart_kb_max: 'Kniebeugen – Max Gewicht (kg)',
    chart_waden_kg: 'Waden – Gewicht (kg)',
    chart_beuger_kg: 'Beuger – Gewicht (kg)',
    chart_hipthrust_kg: 'Hip Thrust – Gewicht (kg)',
    chart_exercises_per: 'Übungen pro Einheit',
    chart_technik_monthly: 'Technikeinheiten pro Monat',
    chart_cat_dist: 'Verteilung nach Kategorie',
    chart_ct_monthly: '{name} pro Monat',
    chart_ct_best_time: 'Beste Zeit pro Einheit',
    chart_ct_reps: 'Wiederholungen pro Einheit',
    chart_ct_kg: 'Kilogramm pro Einheit',
    chart_joggen_trend: 'Laufzeit-Verlauf (5 km)',
    chart_joggen_monthly: 'Joggen-Einheiten pro Monat',
    chart_joggen_pace: 'Pace pro km (Durchschnitt)',
    chart_joggen_avg: 'Ø Laufzeit pro Monat',
    chart_time_trend: 'Trend: Beste Zeit pro Einheit',
    chart_all_times: 'Alle Zeiten im Zeitverlauf',
    chart_monthly_avg: 'Monatsdurchschnitt',
    chart_monthly_best: 'Beste Zeit pro Monat',
    chart_volume: 'Trainingsvolumen pro Monat',
    chart_histogram: 'Zeitverteilung (Histogramm)',
    chart_ni_runs: 'Anzahl Läufe pro Einheit',
    chart_ni_meters: 'Meter pro Einheit (Läufe × {dist}m)',
    chart_ni_runs_month: 'Gesamt-Läufe pro Monat',
    chart_ni_meters_month: 'Gesamt-Meter pro Monat',
    chart_ni_tele: 'Telemarks pro Einheit',
    chart_ni_tele_month: 'Gesamt-Telemarks pro Monat',
    chart_coach_monthly: '{name} – Einheiten/Monat (Saison)',
    chart_coach_dist: '{name} – Trainingsverteilung (Saison)',
    chart_coach_sprint: '{name} – Sprint Bestzeit Trend',
    chart_coach_kb: '{name} – Kniebeugen Max kg',

    // Chart tags
    chart_tag_bar: 'Balken',
    chart_tag_line: 'Linie',
    chart_tag_pie: 'Kreis',

    // Chart axis labels
    axis_sessions: 'Einheiten',
    axis_seconds: 'Sekunden',
    axis_kg: 'Kilogramm',
    axis_exercises: 'Übungen',
    axis_count: 'Anzahl',
    axis_meters: 'Meter',
    axis_telemarks: 'Telemarks',
    axis_frequency: 'Häufigkeit',
    axis_avg_seconds: 'Ø Sekunden',
    axis_best_time: 'Beste Zeit (s)',
    axis_total_runs: 'Gesamtläufe',
    axis_time_mmss: 'Zeit (mm:ss)',
    axis_pace: 'Pace (mm:ss/km)',
    axis_avg_time: 'Ø Zeit (mm:ss)',

    // Chart legends
    legend_sessions: 'Einheiten',
    legend_individual_runs: 'Einzelläufe',
    runs_suffix: 'Läufe',

    // Trends
    trend_better: '↓ Besser',
    trend_slower: '↑ Langsamer',
    trend_stable: '→ Stabil',
    trend_faster: '↓ Schneller',

    // Weekday names
    weekdays: ['So', 'Mo', 'Di', 'Mi', 'Do', 'Fr', 'Sa'],
    weekdays_cal: ['Mo', 'Di', 'Mi', 'Do', 'Fr', 'Sa', 'So'],
    day_order: ['Montag', 'Dienstag', 'Mittwoch', 'Donnerstag', 'Freitag', 'Samstag', 'Sonntag'],
    day_short: { Montag:'Mo', Dienstag:'Di', Mittwoch:'Mi', Donnerstag:'Do', Freitag:'Fr', Samstag:'Sa', Sonntag:'So' },

    // PDF
    pdf_report: 'Wochenbericht',
    pdf_no_training: 'Keine Trainingseinheiten in dieser Woche.',
    pdf_sessions: 'Einheiten',
    pdf_types: 'Trainingsarten',
    pdf_training_days: 'Trainingstage',
    pdf_best_time: 'Beste Zeit',
    pdf_pause_single: 'Pausetag',
    pdf_pause_plural: 'Pausetage',
    pdf_type_section: 'Trainingsarten',
    pdf_best: 'Beste',
    pdf_runs: 'Läufe',
    pdf_exercises: 'Übungen',
    pdf_categories: 'Kategorien',
    pdf_avg_reps: 'Ø Wiederholungen',
    pdf_indiv_sessions: 'Einzelne Einheiten',
    pdf_notes: 'Notizen',
    pdf_footer: 'TrainLytics – trainlytics.de',
    pdf_page: 'Seite {p}/{total}',
    pdf_max: 'Max',
    pdf_wdh: 'Wdh',

    // Settings form
    edit_type: 'Trainingsart bearbeiten',
    no_custom_types: 'Noch keine eigenen Trainingsarten erstellt.',
    no_custom_subcats: 'Keine eigenen Unterkategorien.',
    subcat_name_label: 'Name der Unterkategorie',
    subcat_name_ph: 'z.B. Hürden, 200m, Bergsprints',

    // Coach plan
    no_plans: 'Noch keine Pläne vorhanden',
    week_from_text: 'Woche ab {date}',
    expired: 'abgelaufen',
    active: 'aktiv',
    edit_all: '✏️ Alle bearbeiten',
    delete_all: '🗑️ Alle löschen ({n})',
    no_plan_create: 'Noch kein Plan vorhanden — neuen erstellen',
    sent_plans: '📄 Gesendete Pläne – {name}',
    editing_plan: '✏️ Plan wird bearbeitet',
    editing_plan_for: '✏️ Plan für {name} wird bearbeitet',
    editing_plan_all: '✏️ Plan für ALLE Athleten wird bearbeitet ({n} Athleten)',

    // Coach diary
    no_diary: 'Keine Einträge vorhanden.',
    diary_overview: '📊 Übersicht – {name}',
    diary_entries_label: 'Einträge',
    diary_avg_pain: 'Ø Schmerz',
    diary_most_frequent: 'Häufigste ({n}×)',
    diary_entries: '📋 Einträge',
    diary_load_error: 'Fehler beim Laden.',

    // Injury stats
    injury_total: 'Einträge gesamt',
    injury_avg_pain: 'Ø Schmerzlevel',
    injury_most_frequent: 'Häufigste Stelle ({n}×)',

    // Kraft labels
    kraft_kniebeugen: 'Kniebeugen', kraft_waden: 'Waden', kraft_beuger: 'Beuger',
    kraft_bauch: 'Bauch', kraft_ruecken: 'Rücken', kraft_exzentrisch: 'Exzentrisch', kraft_hipthrust: 'Hip Thrust',

    // calendar tooltip
    cal_training: '🏃 Training',
    cal_comp_prefix: '🏆 ',

    per_week: '/Wo',
    unknown: 'Unbekannt',
    all_athletes_option: '📢 Alle Athleten',
    cat_suffix: ' Kat.',
    coach_avg_week: 'Ø/Woche',
    plan_deleted_multi: 'Plan bei {n} Athleten gelöscht',
    edit_title: 'Bearbeiten',

    // Chat
    chat_title: '📊 Daten-Chat',
    chat_placeholder: 'Frag etwas über deine Daten…',
    chat_welcome: 'Hallo! Ich kann dir Fragen über deine Trainingsdaten beantworten. Schreib einfach los oder tippe <b>/ask</b> für Vorschläge! 💬',
    chat_q_total: 'Wie viele Trainings habe ich?',
    chat_q_rest: 'Wie oft habe ich Pause gemacht?',
    chat_q_streak: 'Was ist mein längster Streak?',
    chat_q_types: 'Welche Trainingsarten mache ich?',
    chat_q_month: 'Wie viele Einheiten diesen Monat?',
    chat_q_pb: 'Was ist mein Sprint-PB?',
    chat_unknown: 'Da bin ich mir nicht sicher 🤔 Versuch es mit anderen Wörtern, z.B. "Pause", "Streak", "Kraft", "PB", "Verletzung" oder "Wettkampf". Tippe <b>/ask</b> für Vorschläge.',
    chat_no_data: 'Es sind noch keine Daten vorhanden.',
    chat_a_total: 'Du hast insgesamt {n} Trainingseinheiten absolviert (ohne Pausetage).',
    chat_a_type_count: 'Du hast {n}× {type} trainiert.',
    chat_a_rest: 'Du hast {n} explizite Pausetage eingetragen.',
    chat_a_rest_full: 'Du hast {pause} Pausetage eingetragen. Insgesamt hattest du {off} Tage ohne Training von {total} Tagen.',
    chat_a_streak: 'Dein längster Trainings-Streak war {n} Tage hintereinander! 🔥',
    chat_a_distribution: 'Deine Trainingsverteilung:',
    chat_a_month: 'Im Monat {month} hast du {n} Trainingseinheiten absolviert.',
    chat_a_week: 'Diese Woche hast du {n} Trainingseinheiten absolviert.',
    chat_a_no_pb: 'Keine Sprint-Daten mit Zeiten vorhanden.',
    chat_a_pb: 'Dein Sprint-PB ist {time} ({type}) am {date} 🏆',
    chat_a_no_kb: 'Keine Kniebeugen-Daten mit Gewichten vorhanden.',
    chat_a_kb: 'Dein maximales Kniebeugen-Gewicht ist {kg} am {date} 💪',
    chat_a_no_jog: 'Keine Joggen-Daten vorhanden.',
    chat_a_jog: 'Du bist {n}× gejoggt. Bestzeit: {best}, Durchschnitt: {avg}.',
    chat_a_no_injuries: 'Keine Verletzungen eingetragen – super! 💪',
    chat_a_injuries: 'Du hast {n} Einträge im Schmerztagebuch. Ø Schmerz: {avg}. Häufigste Stelle: {part}.',
    chat_a_no_comp: 'Keine Wettkämpfe eingetragen.',
    chat_a_comp: 'Du hast {total} Wettkämpfe ({upcoming} bevorstehend, {past} vergangen).',
    chat_a_last: 'Dein letztes Training war {type} am {date}.',
    chat_a_avg: 'Du trainierst im Schnitt {n}× pro Woche.',
    chat_a_intensity: 'Deine Intensitäts-Verteilung:',
    chat_a_notes_hint: 'Schreib ein Stichwort nach "Notiz", z.B. "Notiz Hürden".',
    chat_a_notes_none: 'Kein Eintrag mit "{q}" in den Notizen gefunden.',
    chat_a_notes_found: '{n} Einträge mit "{q}" in den Notizen gefunden.',
    chat_ask_hint: 'Hier sind ein paar Vorschläge:',
},
ro: {
    months: ['Ian','Feb','Mar','Apr','Mai','Iun','Iul','Aug','Sep','Oct','Nov','Dec'],
    locale: 'ro-RO',

    splash_welcome: 'Te antrenezi cu <strong>Micky</strong> și vrei să îți urmărești datele?',
    splash_sub: 'Ești în locul potrivit.',

    login_tagline: 'Aplicația ta pentru antrenament și analiză',
    login_sub: 'Conectează-te pentru a începe',
    login_name_label: 'Numele tău',
    login_name_ph: 'ex. Usain',
    login_pw_label: 'Parolă',
    login_pw_ph: 'Introdu parola',
    login_btn: 'Conectare',
    lang_label: 'Limbă',

    coach_dashboard: 'Panou Antrenor',
    coach_logout: 'Deconectare',
    tab_overview: 'Prezentare',
    tab_plan: 'Plan',
    tab_pain: 'Durere',
    ranking: '🏆 Clasament',
    coach_badge: 'ANTRENOR',
    single_view: '📊 Vizualizare individuală',
    select_athlete: 'Selectează sportivul',
    please_select: '-- Selectează --',
    assign_plan: '📋 Atribuie plan de antrenament',
    athlete: 'Sportiv',
    week_from: 'Săptămâna de la',
    plan_notes_label: 'Observații',
    plan_notes_label_hint: '(opțional)',
    plan_notes_ph: 'Observații generale pentru săptămână…',
    plan_notes_full: 'Observații <span class="label-hint">(opțional)</span>',
    assign_plan_btn: 'Atribuie planul',
    day_mon: 'Luni', day_tue: 'Marți', day_wed: 'Miercuri', day_thu: 'Joi',
    day_fri: 'Vineri', day_sat: 'Sâmbătă', day_sun: 'Duminică',
    day_mon_s: 'Lu', day_tue_s: 'Ma', day_wed_s: 'Mi', day_thu_s: 'Jo',
    day_fri_s: 'Vi', day_sat_s: 'Sâ', day_sun_s: 'Du',
    plan_ph_mon: 'ex. Sprint 6×50m I2', plan_ph_tue: 'ex. Forță', plan_ph_wed: 'ex. Regenerare',
    plan_ph_thu: 'ex. Tempo 120m NI', plan_ph_fri: 'ex. Zi liberă', plan_ph_sat: 'ex. Competiție', plan_ph_sun: 'ex. Liber',
    coach_diary_title: '🩹 Jurnal dureri',

    greeting: 'Salut',
    settings_title: 'Tipuri proprii de antrenament',
    logout: 'Deconectare',

    tab_training: 'Antrenament',
    tab_calendar: 'Calendar',
    tab_analytics: 'Analize',
    tab_diary: 'Jurnal',

    new_session: 'Ședință nouă',
    new_badge: 'NOU',
    date_label: 'Data',
    time_label: 'Ora',
    type_label: 'Tip antrenament',
    category_label: 'Categorie',
    description_label: 'Descriere',
    description_ph: 'ex. Coordonare, garduri...',
    intensity_label: 'Intensitate',
    times_label: 'Timpi',
    times_hint: '(în secunde)',
    time_ph: 'ex. 6.85',
    remove_label: 'Elimină',
    add_time: 'Adaugă timp',
    run_time: 'Timp de alergare',
    minutes_label: 'Minute',
    minutes_ph: 'ex. 28',
    seconds_label: 'Secunde',
    seconds_ph: 'ex. 45',
    count_label: 'Număr alergări',
    count_ph: 'ex. 6',
    weight_label: 'Greutate',
    kg_label: 'Kilograme',
    reps_label: 'Repetări',
    reps_short: 'Rep',
    telemark_question: 'Ai făcut Telemarks?',
    no: 'Nu',
    yes: 'Da',
    telemark_count: 'Număr Telemarks',
    telemark_count_ph: 'ex. 4',
    exercises_label: 'Exerciții',
    exercises_hint: '(bifează ce ai făcut)',
    normal: 'Normal',
    pyramid: 'Piramidă',
    kilo: 'Kilo',
    reps_dot: 'Rep.',
    set_label: 'Set',
    add_set: 'Adaugă set',
    kniebeugen: 'Genuflexiuni',
    waden: 'Gambe',
    beuger: 'Ischiocrurale',
    bauch: 'Abdomen',
    ruecken: 'Spate',
    exzentrisch: 'Excentric',
    hipthrust: 'Hip Thrust',
    add_type_btn: 'Adaugă alt tip de antrenament',
    notes_label: 'Notițe',
    optional_hint: '(opțional)',
    notes_ph: 'Vreme, senzații, suprafață …',
    save_btn: 'Salvează',

    type_sprint: 'Sprint (50m)',
    type_tempo120: 'Tempo (120m)',
    type_tempo150: 'Tempo (150m)',
    type_kraft: 'Forță',
    type_technik: 'Tehnică',
    type_joggen: 'Jogging (5km)',
    type_pause: '💤 Zi de pauză',

    cat_locker: 'Ușor',
    cat_submax: 'Sub-Max',
    cat_max: 'Max',
    cat_seil: 'Frânghie',

    cat_huetchen: 'Conuri',
    cat_schirm: 'Parașut',
    cat_sonstiges: 'Altele',

    history_title: 'Istoric',
    filter_all: 'Toate',
    empty_sessions: 'Nicio ședință înregistrată.',
    clock_suffix: '',
    pausetag_text: 'Zi de pauză 💤',
    runs_count: 'Număr alergări',
    telemarks_label: 'Telemarks',
    count_prefix: 'Număr',
    delete_title: 'Șterge',

    dashboard: 'Tablou de bord',
    analytics_type_label: 'Tip antrenament',
    general: 'General',
    all_categories: 'Toate categoriile',
    all_intensities: 'Toate intensitățile',

    stat_season: 'Sezon',
    stat_sessions_season: 'Ședințe (Sezon)',
    stat_avg_week: 'Ø pe săptămână',
    stat_streak: 'Serie curentă (săpt.)',
    stat_total_all: 'Ședințe Total',
    stat_pause_season: 'Zile pauză (Sezon)',
    stat_last_session: 'Ultima ședință',

    stat_sessions: 'Ședințe',
    stat_avg_exercises: 'Ø Exerciții/Ședință',
    stat_max_kb: 'Max Genuflexiuni (kg)',
    stat_max_waden: 'Max Gambe (kg)',
    stat_most_exercise: 'Cel mai frecvent exercițiu',

    stat_most_category: 'Cea mai frecventă categorie',

    stat_best_time: 'Cel mai bun timp',
    stat_avg_time: 'Ø Timp',
    stat_total_km: 'Total km',
    stat_trend: 'Tendință',

    stat_custom_most_cat: 'Cea mai frecventă categorie',
    stat_custom_last: 'Ultima ședință',

    stat_pb: 'Cel mai bun timp',
    stat_average: 'Medie',
    stat_last5: 'Ultimele 5 ⌀',
    stat_worst: 'Cel mai slab',

    stat_avg_runs: 'Ø Alergări',
    stat_total_runs: 'Total Alergări',
    stat_total_meters: 'Total Metri',
    stat_total_telemarks: 'Total Telemarks',
    stat_avg_telemarks: 'Ø Telemarks',

    pb_title: 'Cele mai bune timpuri personale – Top 10',

    next_comp: 'Următoarea competiție',
    no_comp_planned: 'Nicio competiție planificată',
    add_comp_btn: 'Adaugă competiție',
    season_label: 'Sezon',
    legend_training: 'Antrenament',
    legend_comp: 'Competiție',
    legend_today: 'Azi',
    competitions_title: 'Competiții',
    no_competitions: 'Nicio competiție înregistrată.',
    today_text: 'Azi!',
    tomorrow_text: 'Mâine!',
    days_left: 'Încă {n} zile',

    plan_title: '📋 Plan de antrenament',
    prev_week: 'Săptămâna anterioară',
    next_week: 'Săptămâna următoare',
    add_injury_btn: 'Adaugă durere / accidentare',
    diary_title: '🩺 Jurnal dureri',
    no_diary_entries: 'Niciun articol înregistrat.',
    pain_overview: '📈 Prezentare dureri',

    delete_modal_title: 'Ștergi ședința?',
    delete_modal_text: 'Această acțiune nu poate fi anulată.',
    cancel_btn: 'Anulează',
    delete_btn: 'Șterge',

    comp_modal_title: 'Adaugă competiție',
    comp_name_label: 'Numele competiției',
    comp_name_ph: 'ex. Campionat regional',
    comp_disciplines: 'Discipline',
    comp_weitsprung: 'Săritură în lungime',
    comp_dreisprung: 'Triplu salt',

    injury_modal_title: '🩺 Durere / Accidentare',
    body_part_label: 'Parte a corpului',
    body_select: '-- Selectează --',
    body_knee: 'Genunchi',
    body_thigh: 'Coapsă',
    body_calf: 'Gambă',
    body_ankle: 'Gleznă',
    body_foot: 'Picior',
    body_hip: 'Șold',
    body_back: 'Spate',
    body_shoulder: 'Umăr',
    body_achilles: 'Tendon lui Ahile',
    body_shin: 'Tibie',
    pain_level: 'Nivel durere (1–10)',
    side_label: 'Partea',
    side_left: 'Stânga',
    side_right: 'Dreapta',
    side_both: 'Ambele',

    settings_title_modal: '⚙️ Setări',
    tab_report: '📄 Raport',
    tab_types: '🏷️ Tipuri antrenament',
    report_hint: 'Descarcă un rezumat al săptămânii de antrenament ca PDF.',
    week_label: 'Săptămâna',
    download_pdf: '📥 Descarcă PDF',
    new_type: 'Tip antrenament nou',
    based_on: 'Bazat pe',
    new_category: 'Categorie nouă',
    name_label: 'Nume',
    name_ph: 'ex. Rezistență, Stretching, Garduri',
    emoji_label: 'Emoji',
    emoji_ph: 'ex. 🏋️ 🧘 🔥',
    color_label: 'Culoare',
    subcategories_label: 'Subcategorii',
    subcategories_hint: '(separate prin virgulă, opțional)',
    subcategories_ph: 'ex. Garduri, Coordonare, Sprint',
    track_times: 'Înregistrezi timpii?',
    track_reps: 'Înregistrezi repetările?',
    track_kg: 'Înregistrezi kilogramele?',
    add_btn: 'Adaugă',
    extend_subcats: 'Extinde subcategoriile',
    new_subcat_label: 'Subcategorie nouă',
    new_subcat_ph: 'ex. Garduri, Ștafetă',
    hide_types_title: 'Ascunde tipuri antrenament',
    hide_types_hint: 'Tipurile dezactivate nu apar în formularul de antrenament.',

    toast_pw_required: 'Te rog introdu parola',
    toast_pw_wrong: 'Parolă greșită',
    toast_pw_set: 'Parolă setată ✓',
    toast_login_error_coach: 'Eroare la conectarea antrenorului',
    toast_login_error: 'Eroare la conectare',
    toast_fill_all: 'Te rog completează toate câmpurile',
    toast_select_intensity: 'Te rog selectează intensitatea',
    toast_select_sprint_cat: 'Te rog selectează categoria Sprint',
    toast_select_technik_cat: 'Te rog selectează categoria Tehnică',
    toast_enter_description: 'Te rog introdu descrierea',
    toast_select_category: 'Te rog selectează categoria',
    toast_pause_saved: 'Zi de pauză înregistrată 💤',
    toast_check_exercise: 'Te rog bifează cel puțin un exercițiu',
    toast_valid_runtime: 'Te rog introdu un timp valid',
    toast_valid_times: 'Te rog introdu timpi valizi',
    toast_enter_count: 'Te rog introdu numărul',
    toast_enter_telemark: 'Te rog introdu numărul de Telemarks',
    toast_enter_kg: 'Te rog introdu kilogramele',
    toast_saved: 'Salvat ✓',
    toast_deleted: 'Șters',
    toast_select_week: 'Te rog selectează săptămâna',
    toast_enter_name: 'Te rog introdu numele',
    toast_name_long: 'Numele e prea lung (max 30 caractere)',
    toast_name_reserved: 'Acest nume este rezervat',
    toast_name_taken: 'Numele e deja folosit',
    toast_updated: 'Actualizat ✓',
    toast_added: 'Adăugat ✓',
    toast_removed: 'Eliminat',
    toast_exists: 'Există deja',
    toast_name_too_long: 'Numele e prea lung',
    toast_comp_fill: 'Te rog completează toate câmpurile',
    toast_comp_discipline: 'Te rog selectează cel puțin o disciplină',
    toast_comp_saved: 'Competiție salvată ✓',
    toast_comp_deleted: 'Competiție ștearsă',
    toast_injury_fill: 'Te rog completează data și partea corpului',
    toast_injury_saved: 'Articol salvat ✓',
    toast_injury_deleted: 'Articol șters',
    toast_plan_select: 'Te rog selectează sportivul și săptămâna',
    toast_plan_fill: 'Te rog completează cel puțin o zi',
    toast_plan_assigned_multi: 'Plan atribuit la {n} sportivi ✓',
    toast_plan_assigned: 'Plan atribuit ✓',
    toast_plan_error: 'Eroare la salvare',
    toast_plan_deleted: 'Plan șters',
    toast_plan_delete_error: 'Eroare la ștergere',
    toast_pdf_done: 'PDF descărcat',

    confirm_delete_type: 'Sigur vrei să ștergi tipul "{name}"?',
    confirm_delete_plan_all: 'Sigur ștergi planul ({date}) pentru TOȚI {n} sportivii?',
    confirm_delete_plan: 'Sigur ștergi planul ({date}) pentru {name}?',
    confirm_delete_plan_athlete: 'Sigur ștergi planul pentru săptămâna de la {date}?',

    no_data: 'Fără date',
    no_data_available: 'Nu sunt date disponibile.',
    time_header: 'Timp',
    date_header: 'Data',
    note_header: 'Notă',
    no_athletes: 'Niciun sportiv disponibil.',
    total_sessions: 'Ședințe Total',
    avg_per_week_season: 'Ø Ședințe pe săptămână (Sezon {label})',
    sessions_season: 'Ședințe Sezon ({label})',
    no_entries_athlete: 'Nicio înregistrare disponibilă.',
    stat_total: 'Total',
    sprint_pb: 'PB Sprint',
    max_kb_kg: 'Max GF (kg)',
    additional_type: 'Alt tip de antrenament',

    chart_monthly_season: 'Ședințe pe lună (Sezon {label})',
    chart_type_dist: 'Distribuție pe tip antrenament',
    chart_weekly_season: 'Ședințe pe săptămână (Sezon)',
    chart_weekday: 'Zile de antrenament (pe zi)',
    chart_monthly_all: 'Ședințe pe lună (Total)',
    chart_intensity_dist: 'Distribuție intensitate (Tempo, Sezon)',
    chart_kraft_monthly: 'Ședințe forță pe lună',
    chart_exercise_freq: 'Frecvența exercițiilor (Total)',
    chart_kb_max: 'Genuflexiuni – Greutate max (kg)',
    chart_waden_kg: 'Gambe – Greutate (kg)',
    chart_beuger_kg: 'Ischiocrurale – Greutate (kg)',
    chart_hipthrust_kg: 'Hip Thrust – Greutate (kg)',
    chart_exercises_per: 'Exerciții pe ședință',
    chart_technik_monthly: 'Ședințe tehnică pe lună',
    chart_cat_dist: 'Distribuție pe categorie',
    chart_ct_monthly: '{name} pe lună',
    chart_ct_best_time: 'Cel mai bun timp pe ședință',
    chart_ct_reps: 'Repetări pe ședință',
    chart_ct_kg: 'Kilograme pe ședință',
    chart_joggen_trend: 'Evoluție timp alergare (5 km)',
    chart_joggen_monthly: 'Ședințe jogging pe lună',
    chart_joggen_pace: 'Ritm pe km (medie)',
    chart_joggen_avg: 'Ø Timp alergare pe lună',
    chart_time_trend: 'Tendință: Cel mai bun timp pe ședință',
    chart_all_times: 'Toți timpii în timp',
    chart_monthly_avg: 'Medie lunară',
    chart_monthly_best: 'Cel mai bun timp pe lună',
    chart_volume: 'Volum antrenament pe lună',
    chart_histogram: 'Distribuție timpuri (Histogramă)',
    chart_ni_runs: 'Alergări pe ședință',
    chart_ni_meters: 'Metri pe ședință (Alergări × {dist}m)',
    chart_ni_runs_month: 'Total alergări pe lună',
    chart_ni_meters_month: 'Total metri pe lună',
    chart_ni_tele: 'Telemarks pe ședință',
    chart_ni_tele_month: 'Total Telemarks pe lună',
    chart_coach_monthly: '{name} – Ședințe/Lună (Sezon)',
    chart_coach_dist: '{name} – Distribuție antrenament (Sezon)',
    chart_coach_sprint: '{name} – Tendință PB Sprint',
    chart_coach_kb: '{name} – Genuflexiuni Max kg',

    chart_tag_bar: 'Bare',
    chart_tag_line: 'Linie',
    chart_tag_pie: 'Cerc',

    axis_sessions: 'Ședințe',
    axis_seconds: 'Secunde',
    axis_kg: 'Kilograme',
    axis_exercises: 'Exerciții',
    axis_count: 'Număr',
    axis_meters: 'Metri',
    axis_telemarks: 'Telemarks',
    axis_frequency: 'Frecvență',
    axis_avg_seconds: 'Ø Secunde',
    axis_best_time: 'Cel mai bun (s)',
    axis_total_runs: 'Total alergări',
    axis_time_mmss: 'Timp (mm:ss)',
    axis_pace: 'Ritm (mm:ss/km)',
    axis_avg_time: 'Ø Timp (mm:ss)',

    legend_sessions: 'Ședințe',
    legend_individual_runs: 'Alergări individuale',
    runs_suffix: 'Alergări',

    trend_better: '↓ Mai bun',
    trend_slower: '↑ Mai lent',
    trend_stable: '→ Stabil',
    trend_faster: '↓ Mai rapid',

    weekdays: ['Du', 'Lu', 'Ma', 'Mi', 'Jo', 'Vi', 'Sâ'],
    weekdays_cal: ['Lu', 'Ma', 'Mi', 'Jo', 'Vi', 'Sâ', 'Du'],
    day_order: ['Montag', 'Dienstag', 'Mittwoch', 'Donnerstag', 'Freitag', 'Samstag', 'Sonntag'],
    day_short: { Montag:'Lu', Dienstag:'Ma', Mittwoch:'Mi', Donnerstag:'Jo', Freitag:'Vi', Samstag:'Sâ', Sonntag:'Du' },

    pdf_report: 'Raport săptămânal',
    pdf_no_training: 'Nicio ședință de antrenament în această săptămână.',
    pdf_sessions: 'Ședințe',
    pdf_types: 'Tipuri antrenament',
    pdf_training_days: 'Zile antrenament',
    pdf_best_time: 'Cel mai bun timp',
    pdf_pause_single: 'Zi pauză',
    pdf_pause_plural: 'Zile pauză',
    pdf_type_section: 'Tipuri antrenament',
    pdf_best: 'Cel mai bun',
    pdf_runs: 'Alergări',
    pdf_exercises: 'Exerciții',
    pdf_categories: 'Categorii',
    pdf_avg_reps: 'Ø Repetări',
    pdf_indiv_sessions: 'Ședințe individuale',
    pdf_notes: 'Notițe',
    pdf_footer: 'TrainLytics – trainlytics.de',
    pdf_page: 'Pagina {p}/{total}',
    pdf_max: 'Max',
    pdf_wdh: 'Rep',

    edit_type: 'Editează tip antrenament',
    no_custom_types: 'Niciun tip personalizat creat.',
    no_custom_subcats: 'Nicio subcategorie proprie.',
    subcat_name_label: 'Numele subcategoriei',
    subcat_name_ph: 'ex. Garduri, 200m, Sprint deal',

    no_plans: 'Niciun plan disponibil',
    week_from_text: 'Săptămâna de la {date}',
    expired: 'expirat',
    active: 'activ',
    edit_all: '✏️ Editează toate',
    delete_all: '🗑️ Șterge toate ({n})',
    no_plan_create: 'Niciun plan — creează unul nou',
    sent_plans: '📄 Planuri trimise – {name}',
    editing_plan: '✏️ Plan în editare',
    editing_plan_for: '✏️ Plan pentru {name} în editare',
    editing_plan_all: '✏️ Plan pentru TOȚI sportivii în editare ({n} sportivi)',

    no_diary: 'Nicio înregistrare disponibilă.',
    diary_overview: '📊 Prezentare – {name}',
    diary_entries_label: 'Înregistrări',
    diary_avg_pain: 'Ø Durere',
    diary_most_frequent: 'Cea mai frecventă ({n}×)',
    diary_entries: '📋 Înregistrări',
    diary_load_error: 'Eroare la încărcare.',

    injury_total: 'Total înregistrări',
    injury_avg_pain: 'Ø Nivel durere',
    injury_most_frequent: 'Cea mai frecventă ({n}×)',

    kraft_kniebeugen: 'Genuflexiuni', kraft_waden: 'Gambe', kraft_beuger: 'Ischiocrurale',
    kraft_bauch: 'Abdomen', kraft_ruecken: 'Spate', kraft_exzentrisch: 'Excentric', kraft_hipthrust: 'Hip Thrust',

    cal_training: '🏃 Antrenament',
    cal_comp_prefix: '🏆 ',

    per_week: '/săpt',
    unknown: 'Necunoscut',
    all_athletes_option: '📢 Toți sportivii',
    cat_suffix: ' Cat.',
    coach_avg_week: 'Ø/Săpt',
    plan_deleted_multi: 'Plan șters la {n} sportivi',
    edit_title: 'Editează',

    // Chat
    chat_title: '📊 Chat Date',
    chat_placeholder: 'Întreabă ceva despre datele tale…',
    chat_welcome: 'Salut! Pot să răspund la întrebări despre datele tale de antrenament. Scrie direct sau tastează <b>/ask</b> pentru sugestii! 💬',
    chat_q_total: 'Câte antrenamente am?',
    chat_q_rest: 'Câte pauze am făcut?',
    chat_q_streak: 'Care e cea mai lungă serie?',
    chat_q_types: 'Ce tipuri de antrenament fac?',
    chat_q_month: 'Câte ședințe luna aceasta?',
    chat_q_pb: 'Care e PB-ul meu la sprint?',
    chat_unknown: 'Nu sunt sigur 🤔 Încearcă alte cuvinte, ex. „pauză", „serie", „forță", „PB", „durere" sau „competiție". Tastează <b>/ask</b> pentru sugestii.',
    chat_no_data: 'Nu există date încă.',
    chat_a_total: 'Ai efectuat în total {n} ședințe de antrenament (fără pauze).',
    chat_a_type_count: 'Ai antrenat {type} de {n} ori.',
    chat_a_rest: 'Ai introdus {n} zile de pauză.',
    chat_a_rest_full: 'Ai {pause} zile de pauză. În total, ai avut {off} zile fără antrenament din {total} de zile.',
    chat_a_streak: 'Cea mai lungă serie de antrenament a fost de {n} zile consecutive! 🔥',
    chat_a_distribution: 'Distribuția antrenamentelor tale:',
    chat_a_month: 'În luna {month} ai efectuat {n} ședințe de antrenament.',
    chat_a_week: 'Săptămâna aceasta ai efectuat {n} ședințe de antrenament.',
    chat_a_no_pb: 'Nu există date de sprint cu timpi.',
    chat_a_pb: 'PB-ul tău la sprint este {time} ({type}) pe {date} 🏆',
    chat_a_no_kb: 'Nu există date de genuflexiuni cu greutăți.',
    chat_a_kb: 'Greutatea maximă la genuflexiuni este {kg} pe {date} 💪',
    chat_a_no_jog: 'Nu există date de alergare.',
    chat_a_jog: 'Ai alergat de {n} ori. Cel mai bun timp: {best}, Media: {avg}.',
    chat_a_no_injuries: 'Nicio accidentare înregistrată – super! 💪',
    chat_a_injuries: 'Ai {n} înregistrări în jurnalul de durere. Ø Durere: {avg}. Cea mai frecventă zonă: {part}.',
    chat_a_no_comp: 'Nicio competiție înregistrată.',
    chat_a_comp: 'Ai {total} competiții ({upcoming} viitoare, {past} trecute).',
    chat_a_last: 'Ultimul antrenament a fost {type} pe {date}.',
    chat_a_avg: 'Antrenezi în medie de {n} ori pe săptămână.',
    chat_a_intensity: 'Distribuția intensității tale:',
    chat_a_notes_hint: 'Scrie un cuvânt cheie după „notiță", ex. „notiță garduri".',
    chat_a_notes_none: 'Nicio intrare cu „{q}" în notițe.',
    chat_a_notes_found: '{n} intrări cu „{q}" în notițe găsite.',
    chat_ask_hint: 'Iată câteva sugestii:',
}
};

function t(key, params) {
    let str = TRANSLATIONS[_lang]?.[key] ?? TRANSLATIONS.de[key] ?? key;
    if (params) {
        Object.entries(params).forEach(([k, v]) => {
            str = str.replace(new RegExp('\\{' + k + '\\}', 'g'), v);
        });
    }
    return str;
}

function setLang(lang) {
    _lang = lang;
    localStorage.setItem('trainlytics_lang', lang);
    document.documentElement.lang = lang;
}

function getLang() { return _lang; }
